//
//  FYSSApp.swift
//  FYSS
//
//  Created by vitriol towards YouTube's share sheet and AI on 08/03/26.
//

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - URL handler

/// Handles incoming URLs, extracts the YouTube video link, and forwards it to the configured target.
///
/// Registered as a SwiftUI `@Observable` so that views automatically refresh when any stored
/// property changes. Marked `@MainActor` because all property mutations must happen on the main
/// thread for the observation machinery to work correctly.
@Observable
@MainActor
class URLHandler {

    /// The full raw URL received from the incoming scheme call (e.g. `tg://msg?text=https://...`).
    var lastReceivedURL: String = ""

    /// The YouTube URL decoded from the `text` query parameter of the last incoming URL.
    var lastExtractedURL: String = ""

    /// A human-readable description of the last forwarding attempt (success or error message).
    var lastForwardResult: String = ""

    /// Processes an incoming URL, extracts the YouTube link from the `text` query parameter,
    /// and opens the configured target URL with the extracted link appended.
    ///
    /// - Parameter incomingURL: The URL that caused the app to be opened (e.g. a `tg://` URL
    ///   generated by YouTube's share sheet).
    func handle(_ incomingURL: URL) {
        lastReceivedURL = incomingURL.absoluteString

        // YouTube encodes the video link in the `text` query parameter,
        // e.g. tg://msg?text=https%3A//youtu.be/VIDEO_ID
        let components = URLComponents(url: incomingURL, resolvingAgainstBaseURL: false)
        let extractedPayload = components?.queryItems?.first(where: { $0.name == "text" })?.value
        lastExtractedURL = extractedPayload ?? ""

        let targetBase = (UserDefaults.standard.string(forKey: "targetURL") ?? "").trimmingCharacters(in: .whitespaces)
        let returnToYouTube = UserDefaults.standard.bool(forKey: "returnToYouTube")

        guard !targetBase.isEmpty else {
            lastForwardResult = "Error: no target URL configured."
            return
        }

        guard let payload = extractedPayload, !payload.isEmpty else {
            lastForwardResult = "Error: could not extract payload from incoming URL."
            return
        }

        // Percent-encode the payload so it is safe to embed as a query parameter value.
        // Characters like &, =, +, and # must be encoded to avoid being interpreted as
        // URL structure rather than part of the payload value.
        var allowedCharacters = CharacterSet.urlQueryAllowed
        allowedCharacters.remove(charactersIn: "&=+#")
        let encodedPayload = payload.addingPercentEncoding(withAllowedCharacters: allowedCharacters) ?? payload

        var urlString = targetBase + encodedPayload

        // When "Return to YouTube" is enabled, switch to Shortcuts' x-callback-url scheme
        // and append x-success=youtube:// so the Shortcuts app reopens YouTube on completion.
        // Note: this transformation is only meaningful when the target is a Shortcuts URL
        // (shortcuts://run-shortcut?...). For other targets, only the x-success parameter is
        // appended, which may or may not have any effect depending on the target app.
        if returnToYouTube {
            urlString = urlString.replacingOccurrences(
                of: "shortcuts://run-shortcut?",
                with: "shortcuts://x-callback-url/run-shortcut?"
            )
            urlString += "&x-success=youtube%3A%2F%2F"
        }

        guard let targetURL = URL(string: urlString) else {
            lastForwardResult = "Error: could not construct target URL."
            return
        }

        #if canImport(UIKit)
        // UIApplication.shared.open calls its completion handler on the main thread,
        // but the Task wrapper makes the MainActor requirement explicit for the compiler.
        UIApplication.shared.open(targetURL) { success in
            Task { @MainActor in
                self.lastForwardResult = success
                    ? "Forwarded to \(targetURL.absoluteString)"
                    : "Error: failed to open \(targetURL.absoluteString)"
            }
        }
        #endif
    }
}

// MARK: - App entry point

/// The app entry point. Creates a single `URLHandler` instance shared across the view hierarchy,
/// and wires up `onOpenURL` so every incoming URL is immediately forwarded to the handler.
@main
struct FYSSApp: App {

    /// Shared URL handler injected into the environment and used by `ContentView`.
    @State private var urlHandler = URLHandler()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environment(urlHandler)
                .onOpenURL { url in
                    urlHandler.handle(url)
                }
        }
    }
}
